libbacktrace: update to 2025.04.10 / use XMake buildsystem by default and provide auto-generated CMakeConfig/CMakeVersion files (#7658)
* libbacktrace: update to 2025.04.10

* libbacktrace: use autoconf solution, limit windows

* libbacktrace: use XMake as buildsystem

* libbacktrace: use win32ports unistd_h

* libbacktrace: fix win & validate mingw issue

* libbacktrace: try to make options working

* repair for MinGW
```
checkinfo: ...amdir\core\sandbox\modules\import\core\tool\compiler.lua:84: @programdir\modules\core\tools\gcc.lua:1035: <command-line>:warning: '__GNUC__' redefined
<built-in>: note: this is the location of the previous definition
C:\msys64\tmp\.xmake\250716\_784F4B8C61C543849F341EA5084843DC.c: In function 'main':
C:\msys64\tmp\.xmake\250716\_784F4B8C61C543849F341EA5084843DC.c:9:5: error: built-in function '__sync_synchronize' must be directly called
    9 |     volatile void* p__sync_synchronize = (void*)&__sync_synchronize; if (p__sync_synchronize) {};
      |     ^~~~~~~~
stack traceback:
```

* Do same workaround for HAVE_ATOMIC_FUNCTIONS
```
checkinfo: ...amdir\core\sandbox\modules\import\core\tool\compiler.lua:84: @programdir\modules\core\tools\gcc.lua:1035: C:\msys64\tmp\.xmake\250716\_50F7EE07F29B4102879F2DD383364DD1.c: In function 'main':
C:\msys64\tmp\.xmake\250716\_50F7EE07F29B4102879F2DD383364DD1.c:9:5: error: built-in function '__atomic_store_n' must be directly called
    9 |     volatile void* p__atomic_store_n = (void*)&__atomic_store_n; if (p__atomic_store_n) {};
      |     ^~~~~~~~
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:1075]:
    [@programdir\modules\core\tools\gcc.lua:1035]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
    [@programdir\modules\core\tools\gcc.lua:976]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:246]:
    [@programdir\core\tool\compiler.lua:288]: in function 'compile'
    [...amdir\core\sandbox\modules\import\core\tool\compiler.lua:82]: in function 'compile'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:244]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:246]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:237]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:246]:
    [@programdir\core\project\option.lua:212]: in function '_do_check_cxsnippets'
    [@programdir\core\project\option.lua:264]:
    [@programdir\core\project\option.lua:312]: in function '_check'
    [@programdir\core\project\option.lua:373]: in function 'check'
    [...dir\core\sandbox\modules\import\core\project\project.lua:109]: in function 'jobfunc'
    [@programdir\modules\async\runjobs.lua:247]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:246]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
    [@programdir\modules\async\runjobs.lua:230]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:406]:
```

* re

* resolve windows build

* drop wasm

* just trick wasm compiler

* trick gcc

* fixup

* clr

* Lazy cross limit

* set lang to c11

* simplify so it would reflect correctly

* fixup

* cls

* trick WASM compiler once again because of C11

* keep it always 1.0.0 version

* rename to bitswidth

* rename to bitswidth