Add cairomm (1.14.5, 1.19.0) (#9982)
* Initial commit for cairomm (1.14.5, 1.19.0)

Seems to build but fails the test.
Example error: `cairomm-vc143-1.16.lib(device.cc.obj) : error LNK2019: unresolved external symbol __imp_cairo_device_release referenced in function "public: __cdecl Cairo::Device::Lock::~Lock(void)" (??1Lock@Device@Cairo@@QEAA@XZ)`

* Exclude android, bsd and wasm (dependencies), add pkgconf/pkg-config

Updated cairomm package configuration to include conditional dependencies for Windows and modified installation conditions for specific platforms.

* Add cxxflags

If this makes the tests pass, I still need to investigate whether pkgconf is needed, and whether the define in on_load is needed.

* Attempt to fix windows/mingw shared builds

* Remove pkgconf/pkg-config as a dependency