try to fix
error: ...epositories\xmake-repo-dev\packages\l\libtorch\xmake.lua:182: attempt to compare number with nil
stack traceback:
    [...epositories\xmake-repo-dev\packages\l\libtorch\xmake.lua:182]: in function 'script'
    [...dir\modules\private\action\require\impl\utils\filter.lua:114]: in function 'call'
    [...\modules\private\action\require\impl\actions\install.lua:404]:

  => install libtorch v2.2.2 .. failed